---
application_servers:
  hosts: 
    aws_application_inst: 
      ansible_host: 172.31.45.103
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
web_servers:
  hosts: 
    aws_web_inst: 
      ansible_host: 172.31.36.196
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
access_management_servers:
  hosts: 
    aws_access_management_inst: 
      ansible_host: 172.31.45.137
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
app_database_servers:
  hosts: 
    aws_app_database_inst: 
      ansible_host: 172.31.38.145
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
iam_database_servers:
  hosts: 
    aws_iam_database_inst: 
      ansible_host: 172.31.37.226
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
object_storage_servers:
  hosts: 
    aws_object_storage_inst: 
      ansible_host: 172.31.42.34
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
message_broker_servers:
  hosts: 
    aws_message_broker_inst: 
      ansible_host: 172.31.33.49
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
