---
application_servers:
  hosts: 
    aws_application_inst: 
      ansible_host: 13.39.50.55
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
web_servers:
  hosts: 
    aws_web_inst: 
      ansible_host: 13.39.19.75
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
access_management_servers:
  hosts: 
    aws_access_management_inst: 
      ansible_host: 35.180.190.154
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
app_database_servers:
  hosts: 
    aws_app_database_inst: 
      ansible_host: 35.180.39.139
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
iam_database_servers:
  hosts: 
    aws_iam_database_inst: 
      ansible_host: 13.37.212.230
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
object_storage_servers:
  hosts: 
    aws_object_storage_inst: 
      ansible_host: 35.180.252.36
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
message_broker_servers:
  hosts: 
    aws_message_broker_inst: 
      ansible_host: 35.181.62.242
      ansible_port: 22
      ansible_ssh_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/ec2_rsa
